#
# Copyright 2019, Intel Corporation
#
#

# Pull base image
FROM centos:7
MAINTAINER Brian J. Murrell <brian.murrell@intel.com>

RUN yum install -y epel-release
RUN yum install -y python-requests perl ShellCheck git
RUN yum install -y python3-pip
# Only needed until this PR lands, then it can be removed.
RUN yum install -y python-github

RUN pip3 install codespell
RUN pip3 install pygithub
